# Generated by Django 4.2.3 on 2023-08-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_comment_answer_alter_comment_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='view_cnt',
            field=models.BigIntegerField(default=0),
        ),
    ]
